info:
  app:
    name: membership
    version: 1.0.0-SNAPSHOT
    description:  membership

endpoints:
  shutdown:
    enabled: true
    sensitive: false

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: metrics,health,prometheus
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.byung8.member.mapper
  configuration:
    lazyLoadingEnabled: true
    aggressiveLazyLoading: false
    mapUnderscoreToCamelCase: true
spring:
  profiles:
    active: prod
---
spring:
  profiles: prod
  pid:
    file: /membership/run/membership.pid
  datasource:
    url: jdbc:mysql://mysql.fitness.svc.cluster.local:3306/fitness?useUnicode=yes&characterEncoding=UTF-8
    username: byung8
    password: 1q2w3e4r5t
    driverClassName: com.mysql.jdbc.Driver
logging:
  config: classpath:logback-prod.xml
log:
  file:
    path: "/membership/logs"
server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
---
spring:
  profiles: local
  pid:
    file: E://dev/work/membership/run/membership.pid
  datasource:
    url: jdbc:mysql://192.168.0.2:13306/fitness?useUnicode=yes&characterEncoding=UTF-8
    username: byung8
    password: 1q2w3e4r5t
    driverClassName: com.mysql.jdbc.Driver
logging:
  config: classpath:logback-local.xml
log:
  file:
    path: "E://dev/work/membership/logs"
server:
  port: 8084
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
